before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'danielescarinci.com' >> ~/.ssh/known_hosts
  
stages:
  - deploy

deploy_to_dokku:
  stage: deploy
  script:
    - git remote add dokku dokku@danielescarinci.com:media
    - git push dokku master
